language: c

branches:
  only:
    - master

matrix:
  include:

  - name: Ubuntu Linux 20.04
    os: linux
    dist: focal
    env:
      - CFLAGS="-Werror -g -fno-omit-frame-pointer -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=undefined -fuse-ld=gold"
      - UBSAN_OPTIONS=print_stacktrace=1

script:
  - uname -sr && mkdir build && cd build && cmake .. && cmake --build . && cmake --build . --target test && sudo env "PATH=$PATH" cmake --build . -- install
